In [1]:
class MosquitoesCloud:
    # damage_per_mosquito: float = 1.7
    # mosquitoes_in_cloud: int = 5

    # damage = damage_per_mosquito * mosquitoes_in_cloud

    def __init__(
            self,
            damage_per_mosquito: float = 1.7,
            mosquitoes_in_cloud: int = 5
    ):
        if damage_per_mosquito and mosquitoes_in_cloud is not None:
            self.damage_per_mosquito = damage_per_mosquito
            self.mosquitoes_in_cloud = mosquitoes_in_cloud
            self.damage = damage_per_mosquito * mosquitoes_in_cloud
        else:
            raise ValueError('Please provide correct variables')
        
    def __add__(self: 'MosquitoesCloud', other: 'MosquitoesCloud') -> 'MosquitoesCloud':
        new_mosquitoes_cloud = MosquitoesCloud(
            damage_per_mosquito=(self.damage_per_mosquito + other.damage_per_mosquito) / 2, 
            mosquitoes_in_cloud=self.mosquitoes_in_cloud + other.mosquitoes_in_cloud, 
        )
        return new_mosquitoes_cloud
       

    def __it__(self, other):
        return self.mosquitoes_in_cloud < other.mosquitoes_in_cloud
    

    def __le__(self, other):
        return self.mosquitoes_in_cloud <= other.mosquitoes_in_cloud
    






In [2]:
mcloud1 = MosquitoesCloud()
mcloud1.damage

8.5

In [3]:
mcloud2 = MosquitoesCloud(
    mosquitoes_in_cloud = 10
)
mcloud2.damage

17.0

In [4]:
mcloud3 = mcloud1 + mcloud2
# mcloud3.damage, mcloud3.damage_per_mosquito, mcloud3.mosquitoes_in_cloud



In [5]:
# mcloud1.mosquitoes_in_cloud = 10
# mcloud1.mosquitoes_in_cloud, mcloud2.mosquitoes_in_cloud

In [6]:
mcloud1.mosquitoes_in_cloud < mcloud2.mosquitoes_in_cloud

True

In [7]:
%pip install -Uq numpy


Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

In [9]:
matrix1 = np.array([
    [1, 1, 1],
    [1, 4, 3],
    [11, 12, 13],
    [11, 22, 23]
]
)

In [10]:
matrix2 = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45]
])

In [11]:
matrix1 * 2

array([[ 2,  2,  2],
       [ 2,  8,  6],
       [22, 24, 26],
       [22, 44, 46]])

In [12]:
matrix1 + matrix2

array([[ 5,  6,  7],
       [ 8, 12, 12],
       [88, 24, 25],
       [13, 23, 68]])

In [13]:
matrix1 * matrix2

array([[   4,    5,    6],
       [   7,   32,   27],
       [ 847,  144,  156],
       [  22,   22, 1035]])

In [14]:
class Matrix:
        matrix = []

def test_all(matrix1: Matrix, matrix2: Matrix):
        assert (
        [[1, 1, 1],
        [1, 4, 3],
        [11, 12, 13],
        [11, 22, 23],]
        +
        [[4, 5, 6],
        [7, 8, 9],
        [77, 12, 12],
        [2, 1, 45],]
        ==
        [[ 5,  6,  7],
        [ 8, 12, 12],
        [88, 24, 25],
        [13, 23, 68],]

                
        )
