In [6]:
%pip install -Uq numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
class Matrix:
    def __init__(
    self,
    matrix,
):
        self.matrix = matrix


    def T(self, other = None):
        new_matrix = [[self.matrix[j][i] for j in range(len(self.matrix))] for i in range(len(self.matrix[0]))]
        if other != None:
            new_matrix = [[other.matrix[j][i] for j in range(len(other.matrix))] for i in range(len(other.matrix[0]))]
            return new_matrix
        else:
            new_matrix = [[self.matrix[j][i] for j in range(len(self.matrix))] for i in range(len(self.matrix[0]))]
            return Matrix(new_matrix)
        
    def Trans(self, other = None):
        new_matrix = [[self.matrix[j][i] for j in range(len(self.matrix))] for i in range(len(self.matrix[0]))]
        if other != None:
            new_matrix = [[other.matrix[j][i] for j in range(len(other.matrix))] for i in range(len(other.matrix[0]))]
            return new_matrix
        else:
            new_matrix = [[self.matrix[j][i] for j in range(len(self.matrix))] for i in range(len(self.matrix[0]))]
            return new_matrix


    def __add__(self: list, other: list | float | int) -> list | float | int:
        
        if type(other) == float or type(other) == int:
            num_cols = len(self.matrix)
            num_rows = len(self.matrix[0])
            sum_N = []
            sum_N = [[0 for row in range(num_rows)] for col in range(num_cols)]

            for i in range(num_cols):
                for j in range(num_rows):
                    sum_N[i][j] = self.matrix[i][j] + other
            return sum_N
    
        else:
            sum = []
            num_cols = len(self.matrix)
            num_rows = len(other.matrix[0])
            sum = [[0 for row in range(num_rows)] for col in range(num_cols)]

            if len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0]):    
                for i in range(num_cols):
                    for j in range(num_rows):
                        sum[i][j] = self.matrix[i][j] + other.matrix[i][j]
                return sum
            else:
                raise ValueError('Матрицы должны иметь одинаковое колличество строк и колонок, чтобы их можно было слкадывать')


    def __sub__(self: list, other: list | float | int) -> list | float | int:
        if type(other) == float or type(other) == int:
            num_cols = len(self.matrix)
            num_rows = len(self.matrix[0])
            sum_N = []
            sum_N = [[0 for row in range(num_rows)] for col in range(num_cols)]

            for i in range(num_cols):
                for j in range(num_rows):
                    sum_N[i][j] = self.matrix[i][j] - other
            return sum_N
        else:
            if len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0]):   
                minus = []
                num_cols = len(self.matrix)
                num_rows = len(other.matrix[0])
                minus = [[0 for row in range(num_rows)] for col in range(num_cols)]    
                for i in range(num_cols):
                    for j in range(num_rows):
                        minus[i][j] = self.matrix[i][j] - other.matrix[i][j]
                return minus
            else:
                raise ValueError('Матрицы должны иметь одинаковое колличество строк и колонок, чтобы значения одной можно было вычесть из другой')
    

    def __mul__(self: list, other: list | float | int) -> list | float | int:

        if type(other) == float or type(other) == int:
            num_cols = len(self.matrix)
            num_rows = len(self.matrix[0])
            sum_N = []
            sum_N = [[0 for row in range(num_rows)] for col in range(num_cols)]

            for i in range(num_cols):
                for j in range(num_rows):
                    sum_N[i][j] = self.matrix[i][j] * other
            return sum_N
        
        else:
            if len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0]):
                mult = []  
                num_cols = len(self.matrix)
                num_rows = len(other.matrix[0]) 
                mult = [[0 for row in range(num_rows)] for col in range(num_cols)]
                for i in range(num_cols):
                    for j in range(num_rows):
                        mult[i][j] = self.matrix[i][j] * other.matrix[i][j]
                return mult
            else:
                raise ValueError('Матрицы должны иметь одинаковое колличество строк и колонок, чтобы их значения можно было умножить')


    def __truediv__(self: list, other: list | float | int) -> list | float | int:

        if type(other) == float or type(other) == int:
            num_cols = len(self.matrix)
            num_rows = len(self.matrix[0])
            sum_N = []
            sum_N = [[0 for row in range(num_rows)] for col in range(num_cols)]

            for i in range(num_cols):
                for j in range(num_rows):
                    sum_N[i][j] = self.matrix[i][j] / other
            return sum_N
        
        else:
            if len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0]):
                div = []
                num_cols = len(self.matrix)
                num_rows = len(other.matrix[0])  
                div = [[0 for row in range(num_rows)] for col in range(num_cols)]  
                for i in range(num_cols):
                    for j in range(num_rows):
                        div[i][j] = self.matrix[i][j] / other.matrix[i][j]
                return div
            else: 
                raise ValueError('Матрицы должны иметь одинаковое колличество строк и колонок, чтобы их значения можно было разделить друг на друга')


    def __matmul__(self: list, other: list) -> list:
        if len(other.matrix) > len(self.matrix):
            other.matrix = self.T(other)
        # rows1 = len(self.matrix)
        # cols1= len(self.matrix[0]) 
        # rows2 = len(other.matrix)
        # cols2 = len(other.matrix[0]) 
        result = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(other.matrix[0])):
                val = 0
                for k in range(len(other.matrix)):
                    val += self.matrix[i][k] * other.matrix[k][j]
                row.append(val)
            result.append(row)
        return (result)
    

In [9]:
matrix1 = Matrix([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],
])

matrix1.T()

In [10]:
matrix1 = Matrix([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],
])

matrix2 = Matrix([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45],
])

matrix1 == matrix2

False

In [11]:
matrix1 = Matrix([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],
])

matrix2 = Matrix([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45],
])

matrix1 + matrix2

# для проверки +, -, / просто меняю знак 

[[5, 6, 7], [8, 10, 12], [88, 24, 25], [13, 23, 78]]

In [12]:
npmatrix1 = np.array([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],
])

npmatrix2 = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45],
])

npmatrix1 + npmatrix2

array([[ 5,  6,  7],
       [ 8, 10, 12],
       [88, 24, 25],
       [13, 23, 78]])

In [13]:
matrix1 = Matrix([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],
])

matrix1 + 2

# для проверки +, -, / просто меняю знак  и число

[[3, 3, 3], [3, 4, 5], [13, 14, 15], [13, 24, 35]]

In [14]:
npmatrix1 = np.array([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],
])

npmatrix1 + 2

array([[ 3,  3,  3],
       [ 3,  4,  5],
       [13, 14, 15],
       [13, 24, 35]])

In [15]:
matrix1 = Matrix([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45],
])

matrix2 = Matrix([
    [1, 1, 1, 2],
    [1, 2, 3, 0],
    [11, 12, 13, 0],
])

matrix1 @ matrix2

[[75, 86, 97, 8],
 [114, 131, 148, 14],
 [221, 245, 269, 154],
 [498, 544, 590, 4]]

In [16]:
npmatrix1 = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 45],
])

npmatrix2 = np.array([
    [1, 1, 1, 2],
    [1, 2, 3, 0],
    [11, 12, 13, 0],
])

npmatrix1 @ npmatrix2


array([[ 75,  86,  97,   8],
       [114, 131, 148,  14],
       [221, 245, 269, 154],
       [498, 544, 590,   4]])

In [17]:
%pip install -q ipytest pytest

import ipytest
import pytest
ipytest.autoconfig()

Note: you may need to restart the kernel to use updated packages.


In [18]:
%%ipytest

matrix1 = Matrix([
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
])

matrix2 = Matrix([
    [4, 5, 6,],
    [7, 8, 9],
    [77, 12, 12],
])

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 + matrix2 == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 + number == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 - matrix2 == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 - number == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (matrix1.Trans() == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 * matrix2 == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 * number == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 / matrix2 == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 / number == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (matrix1 @ matrix2 == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'
    
    


..........                                                                                   [100%]
10 passed in 0.04s
